'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rental_data_captured
    Public Property key_id As Integer
    Public Property site_title As String
    Public Property business_type As String
    Public Property company_name As String
    Public Property address As String
    Public Property city As String
    Public Property province As String
    Public Property postalcode As String
    Public Property num_bedrooms As Integer
    Public Property rent_amount As Decimal
    Public Property incentive As String
    Public Property num_bathrooms As Decimal
    Public Property square_footage As Nullable(Of Integer)
    Public Property year_built As Nullable(Of Integer)
    Public Property availability As Nullable(Of Date)
    Public Property num_units As Nullable(Of Integer)
    Public Property electricity As Nullable(Of Boolean)
    Public Property electricity_extra As Nullable(Of Decimal)
    Public Property heating As Nullable(Of Boolean)
    Public Property heating_type As String
    Public Property heating_extra As Nullable(Of Decimal)
    Public Property hot_water As Nullable(Of Boolean)
    Public Property hot_water_extra As Nullable(Of Decimal)
    Public Property laundry_type As String
    Public Property cable As Nullable(Of Boolean)
    Public Property cable_extra As Nullable(Of Decimal)
    Public Property internet As Nullable(Of Boolean)
    Public Property internet_extra As Nullable(Of Decimal)
    Public Property storage As Nullable(Of Boolean)
    Public Property storage_extra As Nullable(Of Decimal)
    Public Property pets As Nullable(Of Boolean)
    Public Property pets_extra As Nullable(Of Decimal)
    Public Property pets_comments As String
    Public Property parking_type As String
    Public Property parking_extra As Nullable(Of Decimal)
    Public Property has_elevator As Nullable(Of Boolean)
    Public Property has_month_to_month_lease As Nullable(Of Boolean)
    Public Property security_deposit As Nullable(Of Decimal)
    Public Property senior_discount As Nullable(Of Decimal)
    Public Property website As String
    Public Property has_aircon As Nullable(Of Boolean)
    Public Property has_dishwasher As Nullable(Of Boolean)
    Public Property has_washer As Nullable(Of Boolean)
    Public Property has_dryer As Nullable(Of Boolean)
    Public Property has_stove As Nullable(Of Boolean)
    Public Property has_fridge As Nullable(Of Boolean)
    Public Property has_microwave As Nullable(Of Boolean)
    Public Property has_furniture As Nullable(Of Boolean)
    Public Property has_common_room As Nullable(Of Boolean)
    Public Property has_exercise_room As Nullable(Of Boolean)
    Public Property has_pool As Nullable(Of Boolean)
    Public Property has_adults_only As Nullable(Of Boolean)
    Public Property has_den As Nullable(Of Boolean)
    Public Property has_balcony As Nullable(Of Boolean)
    Public Property has_smoking As Nullable(Of Boolean)
    Public Property near_parks As Nullable(Of Boolean)
    Public Property near_hospital As Nullable(Of Boolean)
    Public Property near_school As Nullable(Of Boolean)
    Public Property near_church As Nullable(Of Boolean)
    Public Property near_fire_department As Nullable(Of Boolean)
    Public Property near_transit As Nullable(Of Boolean)
    Public Property near_mall As Nullable(Of Boolean)
    Public Property near_police As Nullable(Of Boolean)
    Public Property near_ambulance As Nullable(Of Boolean)
    Public Property created_by As String
    Public Property created_timestamp As Date
    Public Property powered_parking As Nullable(Of Boolean)
    Public Property parking_stalls_included As Nullable(Of Integer)
    Public Property secure_parking As Nullable(Of Boolean)
    Public Property contact_info As String
    Public Property longitude As Nullable(Of Double)
    Public Property latitude As Nullable(Of Double)
    Public Property point As System.Data.Entity.Spatial.DbGeometry
    Public Property sent_to_AGOL As Nullable(Of Date)

End Class
